Made script more versitile.

diff --git a/plantlogbuild b/plantlogbuild
--- a/plantlogbuild
+++ b/plantlogbuild
@@ -3,12 +3,12 @@ set -o posix;
 BUILD_PATH="./";
 
 function logging_mode {
-    docker run -p 80:8080 my_server;
+    docker run -p 80:8080 $1;
 }
 
 # Builds the docker image
 function build {
-    if ! docker build -t my_server $BUILD_PATH; then
+    if ! docker build -t $1 $BUILD_PATH; then
         echo "Unable to build docker container in $BUILD_PATH";
     fi
     echo "Successfully built docker container";
@@ -16,8 +16,8 @@ function build {
 
 # Rus the plantlog docker image
 function run_image {
-    if ! docker run -d -p 80:8080 my_server; then
-        echo "Couldn't start the server, exiting...";
+    if ! docker run -d -p 80:8080 $1; then
+        echo "Couldn't start the server $1, exiting...";
         exit 1;
     fi
     echo "Docker image started, should be live at http://localhost";
@@ -25,27 +25,30 @@ function run_image {
 
 # Quick rebuild: just rebuild the container
 function quick_rebuild {
-    echo "Quick Rebuild of container $1";
-    echo "Stopping container $1";
-    docker stop $1;
-    echo "Deleting old container $1";
-    docker rmi -f $1;
+    container_id=$(docker images -q $1);
+    echo "Quick Rebuild of image $1";
+    echo "Stopping container $container_id";
+    docker stop $container_id;
+    echo "Deleting old container $container_id";
+    docker rmi -f $container_id;
     echo "Building new container";
-    docker build -t my_server $BUILD_PATH;
+    docker build -t $1 $BUILD_PATH;
     echo "Starting server!";
-    docker run -d -p 80:8080 my_server;
+    docker run -d -p 80:8080 $1;
     echo "Server should be up at http://localhost";
 }
 
 # Full Rebuild: rebuild the entire docker system including clearing caches
 function full_rebuild {
-    echo "Full rebuild of $1";
-    echo "Stopping container $1";
-    docker stop $1;
-    echo "rebuilding container";
-    docker build --no-cache -t my_server $BUILD_PATH;
+    container_id=$(docker images -q $1);
+    echo $container_id;
+    echo "Full rebuild of image $1";
+    echo "Stopping container $container_id";
+    docker stop $container_id;
+    echo "Rebuilding image $1";
+    docker build --no-cache -t $1 $BUILD_PATH;
     echo "Starting server!";
-    docker run -d -p 80:8080 my_server;
+    docker run -d -p 80:8080 $1;
     echo "Server should be up at http://localhost";
 }
 
@@ -53,21 +56,21 @@ function show_help {
     echo "+----------------------------------------------------------------------+";
     echo "|                     Plantlog build helper script                     |";
     echo "+----------------------------------------------------------------------+";
-    echo "|            -b - Just build the image                                 |";
-    echo "|            -q [container id] - Quick rebuild the image               |";
-    echo "|            -f [container id] - Full rebuild with --no-cache          |";
-    echo "|            -r - Run the plantlog docker image                        |";
+    echo "|            -b [container name] - Just build the image                |";
+    echo "|            -q [container name] - Quick rebuild the image             |";
+    echo "|            -f [container name] - Full rebuild with --no-cache        |";
+    echo "|            -r [container name] - Run the plantlog docker image       |";
     echo "|            -h - Print this help message then exit                    |";
     echo "+----------------------------------------------------------------------+";
 }
 
-while getopts "q:f:blrh" arg; do
+while getopts "q:f:b:l:r:h" arg; do
     case "$arg" in
-        b) build;;
+        b) build ${OPTARG};;
         q) quick_rebuild ${OPTARG};;
         f) full_rebuild ${OPTARG};;
-        r) run_image;;
-        l) logging_mode;;
+        r) run_image ${OPTARG};;
+        l) logging_mode ${OPTARG};;
         h) show_help;;
         ?) show_help;;
         *) echo "Something went wront, exiting....";;
